version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g @nestjs/cli
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 350905989109.dkr.ecr.eu-north-1.amazonaws.com
      - REPOSITORY_URI=350905989109.dkr.ecr.eu-north-1.amazonaws.com/nestjs-new-app-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"demo-app","imageUri":"$REPOSITORY_URI:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json